apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adaptdl-sched
  labels:
    app: adaptdl-sched
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: adaptdl-sched
    release: {{ .Release.Name }}
