{
 "title": "Dynamic Resource Auto-Tuner",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(job_replicas, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Resource Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Nodes" }
   ],
   "targets": [
    { "expr": "job_replicas", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Details for $job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Loss" }
   ],
   "targets": [
    {
     "expr": "job_train_loss{job=\"$job\"}",
     "legendFormat": "Train"
    },
    {
     "expr": "job_valid_loss{job=\"$job\"}",
     "legendFormat": "Valid"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_replicas{job=\"$job\"}",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "Global Batch Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_replicas{job=\"$job\"} * job_local_bsz{job=\"$job\"}",
     "legendFormat": "global_bsz"
    }
   ]
  },
  {
   "title": "Local Batch Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_local_bsz{job=\"$job\"}",
     "legendFormat": "local_bsz"
    }
   ]
  },
  {
   "title": "Time per Step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "(job_profiled_time_total{job=\"$job\"} - job_profiled_time_sync{job=\"$job\"}) / job_profiled_steps{job=\"$job\"}",
     "legendFormat": "Compute"
    },
    {
     "expr": "job_profiled_time_sync{job=\"$job\"} / job_profiled_steps{job=\"$job\"}",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "Predicted Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "steps/sec" }
   ],
   "targets": [
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"1\"}",
     "legendFormat": "1"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"2\"}",
     "legendFormat": "2"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"3\"}",
     "legendFormat": "3"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"4\"}",
     "legendFormat": "4"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"5\"}",
     "legendFormat": "5"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"6\"}",
     "legendFormat": "6"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"7\"}",
     "legendFormat": "7"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"8\"}",
     "legendFormat": "8"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"9\"}",
     "legendFormat": "9"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"10\"}",
     "legendFormat": "10"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"11\"}",
     "legendFormat": "11"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"12\"}",
     "legendFormat": "12"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"13\"}",
     "legendFormat": "13"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"14\"}",
     "legendFormat": "14"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"15\"}",
     "legendFormat": "15"
    },
    {
     "expr": "job_perf_predict{job=\"$job\",replicas=\"16\"}",
     "legendFormat": "16"
    }
   ]
  }
 ]
}