# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest-cov==2.6.1 coverage -r requirements-test.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 adaptdl cli cli/bin/adaptdl sched --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 adaptdl cli cli/bin/adaptdl sched --exclude cli/adaptdl_cli/__init__.py
    - name: Build and install train package
      run: |
        pip install -e ./adaptdl
    - name: Build and install sched package
      run: |
        pip install -e ./sched
    - name: Build and install CLI package
      run: |
        pip install -e ./cli
    - name: Test sched
      run: |
        pytest sched -xv --cov=sched --cov-branch --cov-report=
        mv .coverage .coverage.sched
    - name: Test train
      run: |
        pytest adaptdl -xv --ignore=adaptdl/speedup_test.py --cov=adaptdl --cov-branch --cov-report=
        mv .coverage .coverage.train
    - name: Coverage
      run: |
        coverage combine
        coverage report -m --omit="**/*test.py"
        coverage html --omit="**/*test.py"
        coverage xml --omit="**/*test.py"  -o htmlcov/coverage.xml
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: htmlcov/coverage.xml
        name: adaptdl
        fail_ci_if_error: true # optional (default = false)
